### PR TITLE
Suppress email alerts that have been seen too recently

### PR DESCRIPTION
**Pull request by robn**

### CODE REVIEW

**Comment by robn** [comment]
@Davis-A what do you think?

**Comment by Davis-A** [comment]
Looks like it does what it says on the tin.

Can you also make it send a final "alert has ended" email when the alert is no longer active.  

While you're in there, can you make it send a final ✔️ email saying the alert has resolved when it resolves.

**Comment by Davis-A** [comment]
(because this is under your namespace, unless you list me as a reviewer i can't click review buttons only shit talk you in the comments)

**Comment by robn** [comment]
Yeah, it wouldn't let me make you a reviewer. I don't get it.

It'll still send a final email as it does now, but there's no detail in it. I'll be doing that in a separate PR.

**Pull request merged**
